package bootstrap

import (
	"fmt"
	"path/filepath"
	"strings"
)

const (
	BootstrapMethodSnapshot = "snapshot"
	BootstrapMethodMithril  = "mithril"
)

type RunbookOptions struct {
	WorkDir         string
	ConfigPath      string
	MySQLCompose    string
	MySQLDSN        string
	Driver          string
	Profile         string
	BootstrapMethod string
	SnapshotVariant string
	SnapshotPoint   string
}

func NormalizeBootstrapMethod(method string) string {
	switch strings.ToLower(strings.TrimSpace(method)) {
	case "", BootstrapMethodSnapshot:
		return BootstrapMethodSnapshot
	case BootstrapMethodMithril:
		return BootstrapMethodMithril
	default:
		return strings.ToLower(strings.TrimSpace(method))
	}
}

func GenerateRunbook(report *DolosReport, options RunbookOptions) (string, error) {
	if report == nil {
		return "", fmt.Errorf("dolos report is required")
	}
	options = normalizeRunbookOptions(report, options)
	if err := validateRunbookOptions(options); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Nectar Dolos/Mithril Bootstrap Runbook\n\n")
	b.WriteString("This runbook is generated by `nectar bootstrap-dolos`. It is safe to generate while a snapshot is still downloading because it does not execute any command.\n\n")
	b.WriteString("## Current Dolos State\n\n")
	fmt.Fprintf(&b, "- Dolos directory: `%s`\n", report.Dir)
	fmt.Fprintf(&b, "- Dolos config: `%s`\n", report.ConfigPath)
	fmt.Fprintf(&b, "- Storage: `%s`\n", report.StoragePath)
	fmt.Fprintf(&b, "- Archive segments: `%d`\n", report.ArchiveSegments)
	fmt.Fprintf(&b, "- Socket: `%s` (%s)\n", report.SocketPath, readyWord(report.SocketReady))
	fmt.Fprintf(&b, "- UTxO RPC endpoint: `%s` (%s)\n", report.GRPCEndpoint, configuredWord(report.GRPCConfigured))
	fmt.Fprintf(&b, "- Ready for config generation: `%t`\n", report.ReadyForConfig)
	fmt.Fprintf(&b, "- Ready for live import: `%t`\n\n", report.ReadyForLiveImport)

	b.WriteString("## Commands\n\n")
	b.WriteString("Run these manually, in order, after confirming the previous step completed successfully.\n\n")
	writeCommandBlock(&b, "1. Continue or resume Dolos snapshot bootstrap", dolosBootstrapCommand(report, options))
	writeCommandBlock(&b, "2. Start Dolos after bootstrap completes", dolosDaemonCommand(report))
	writeCommandBlock(&b, "3. Confirm Dolos socket and UTxO RPC readiness", fmt.Sprintf("go run . bootstrap-dolos --dolos-dir %s --require-socket", shellQuote(report.Dir)))
	writeCommandBlock(&b, "4. Start the MySQL evaluation database if it is not already running", fmt.Sprintf("docker compose -f %s up -d", shellQuote(options.MySQLCompose)))
	writeCommandBlock(&b, "5. Generate Nectar config for Honeycomb tables", nectarConfigCommand(report, options))
	writeCommandBlock(&b, "6. Dry-run current UTxO import before writing SQL", fmt.Sprintf("go run . snapshot-import --config %s --dolos-dir %s --limit 1000", shellQuote(options.ConfigPath), shellQuote(report.Dir)))
	writeCommandBlock(&b, "7. Apply current UTxO seed into Nectar/Honeycomb tables", fmt.Sprintf("go run . snapshot-import --config %s --dolos-dir %s --apply --replace-utxo", shellQuote(options.ConfigPath), shellQuote(report.Dir)))
	writeCommandBlock(&b, "8. Dry-run Dolos historical block decode", fmt.Sprintf("go run . history-import --config %s --dolos-dir %s --limit 100", shellQuote(options.ConfigPath), shellQuote(report.Dir)))
	writeCommandBlock(&b, "9. Apply Dolos historical blocks into Nectar tables", fmt.Sprintf("go run . history-import --config %s --dolos-dir %s --apply --history-commit-blocks 100", shellQuote(options.ConfigPath), shellQuote(report.Dir)))
	writeCommandBlock(&b, "10. Check historical import progress", fmt.Sprintf("go run . history-import --config %s --status", shellQuote(options.ConfigPath)))
	writeCommandBlock(&b, "11. Verify historical tables and indexes", fmt.Sprintf("go run . verify-history --config %s --deep --require-complete", shellQuote(options.ConfigPath)))
	writeCommandBlock(&b, "12. Rebuild product tables", fmt.Sprintf("go run . rebuild-products --config %s --tables all", shellQuote(options.ConfigPath)))
	writeCommandBlock(&b, "13. Verify product table consistency", fmt.Sprintf("go run . verify-products --config %s --deep", shellQuote(options.ConfigPath)))
	writeCommandBlock(&b, "14. Start Nectar live ChainSync follower", fmt.Sprintf("NECTAR_NO_DASHBOARD=true SKIP_MIGRATIONS=true go run . --config %s", shellQuote(options.ConfigPath)))
	writeCommandBlock(&b, "15. Verify indexed max slot is close to Dolos tip", fmt.Sprintf("go run . verify-history --config %s --dolos-dir %s --deep --require-complete --require-tip", shellQuote(options.ConfigPath), shellQuote(report.Dir)))

	b.WriteString("## Notes\n\n")
	b.WriteString("- `snapshot-import` full unfiltered apply seeds current UTxO holder state into Nectar SQL tables and refreshes `token_holders` directly from the current UTxO set.\n")
	b.WriteString("- Partial `--apply` with `--limit` or asset filters is refused unless `--allow-partial-apply` is passed for tests.\n")
	b.WriteString("- Historical wallet graph data comes from `history-import`, which replays Dolos `DumpHistory` archive blocks into Nectar's `BlockProcessor`.\n")
	b.WriteString("- `verify-history --deep --require-complete` is the base-table/index gate before product rebuild claims success.\n")
	b.WriteString("- `verify-products --deep` reconciles token holders, ADA wallet graph rows, and token wallet graph rows against indexed base tables.\n")
	b.WriteString("- Dolos socket ChainSync remains the live tailing path after historical catch-up; `verify-history --require-tip` proves it is close to Dolos' current tip.\n")
	b.WriteString("- Rewards are not populated or estimated by the snapshot import path.\n")
	b.WriteString("- If an extracted snapshot contains UTxO-HD `ledger/<slot>/tables/tvar`, `snapshot-import --source filesystem --apply --replace-utxo` can seed the same current UTxO tables without Dolos UTxO RPC.\n")
	b.WriteString("- The UTxO-HD `tables/tvar` importer memory-maps the file to avoid copying a mainnet-sized table into the Go heap.\n")
	b.WriteString("- Legacy ledger-state file decode is intentionally separate from the Dolos UTxO-RPC and UTxO-HD `tables/tvar` import paths.\n")
	return b.String(), nil
}

func GenerateScript(report *DolosReport, options RunbookOptions) (string, error) {
	if report == nil {
		return "", fmt.Errorf("dolos report is required")
	}
	options = normalizeRunbookOptions(report, options)
	if err := validateRunbookOptions(options); err != nil {
		return "", err
	}

	lines := []string{
		"#!/usr/bin/env bash",
		"set -euo pipefail",
		"",
		"# Generated by `nectar bootstrap-dolos`. Review before running.",
		fmt.Sprintf("cd %s", shellQuote(options.WorkDir)),
		"",
		"echo '1/8 continuing Dolos snapshot bootstrap'",
		dolosBootstrapCommand(report, options),
		"",
		"echo '2/8 start Dolos in a separate terminal when bootstrap is complete'",
		fmt.Sprintf("echo %s", shellQuote(dolosDaemonCommand(report))),
		"read -r -p 'Press Enter after Dolos socket and UTxO RPC are serving... '",
		"",
		"echo '3/8 confirming Dolos socket readiness'",
		fmt.Sprintf("go run . bootstrap-dolos --dolos-dir %s --require-socket", shellQuote(report.Dir)),
		"",
		"echo '4/8 starting MySQL evaluation database if needed'",
		fmt.Sprintf("docker compose -f %s up -d", shellQuote(options.MySQLCompose)),
		"",
		"echo '5/8 generating Nectar config'",
		nectarConfigCommand(report, options),
		"",
		"echo '6/8 dry-running current UTxO import'",
		fmt.Sprintf("go run . snapshot-import --config %s --dolos-dir %s --limit 1000", shellQuote(options.ConfigPath), shellQuote(report.Dir)),
		"",
		"echo '7/8 applying current UTxO seed'",
		fmt.Sprintf("go run . snapshot-import --config %s --dolos-dir %s --apply --replace-utxo", shellQuote(options.ConfigPath), shellQuote(report.Dir)),
		"",
		"echo '8/9 importing historical blocks and verifying product tables'",
		fmt.Sprintf("go run . history-import --config %s --dolos-dir %s --limit 100", shellQuote(options.ConfigPath), shellQuote(report.Dir)),
		fmt.Sprintf("go run . history-import --config %s --dolos-dir %s --apply --history-commit-blocks 100", shellQuote(options.ConfigPath), shellQuote(report.Dir)),
		fmt.Sprintf("go run . history-import --config %s --status", shellQuote(options.ConfigPath)),
		fmt.Sprintf("go run . verify-history --config %s --deep --require-complete", shellQuote(options.ConfigPath)),
		fmt.Sprintf("go run . rebuild-products --config %s --tables all", shellQuote(options.ConfigPath)),
		fmt.Sprintf("go run . verify-products --config %s --deep", shellQuote(options.ConfigPath)),
		"",
		"echo '9/9 start live ChainSync follower separately, then verify tip lag'",
		fmt.Sprintf("echo %s", shellQuote(fmt.Sprintf("NECTAR_NO_DASHBOARD=true SKIP_MIGRATIONS=true go run . --config %s", shellQuote(options.ConfigPath)))),
		"read -r -p 'Press Enter after live ChainSync has started and caught up... '",
		fmt.Sprintf("go run . verify-history --config %s --dolos-dir %s --deep --require-complete --require-tip", shellQuote(options.ConfigPath), shellQuote(report.Dir)),
		"",
	}
	return strings.Join(lines, "\n"), nil
}

func normalizeRunbookOptions(report *DolosReport, options RunbookOptions) RunbookOptions {
	if strings.TrimSpace(options.WorkDir) == "" {
		options.WorkDir = "."
	}
	if strings.TrimSpace(options.ConfigPath) == "" {
		options.ConfigPath = "nectar.toml"
	}
	if strings.TrimSpace(options.MySQLCompose) == "" {
		options.MySQLCompose = "docker-compose.mysql.example.yml"
	}
	if strings.TrimSpace(options.Driver) == "" {
		options.Driver = "mysql"
	}
	if strings.TrimSpace(options.Profile) == "" {
		options.Profile = "honeycomb"
	}
	options.BootstrapMethod = NormalizeBootstrapMethod(options.BootstrapMethod)
	if strings.TrimSpace(options.SnapshotVariant) == "" {
		options.SnapshotVariant = "full"
	}
	if strings.TrimSpace(options.SnapshotPoint) == "" {
		options.SnapshotPoint = "latest"
	}
	if !filepath.IsAbs(options.ConfigPath) {
		options.ConfigPath = filepath.Clean(options.ConfigPath)
	}
	if report != nil && report.Dir != "" && !filepath.IsAbs(options.MySQLCompose) {
		options.MySQLCompose = filepath.Clean(options.MySQLCompose)
	}
	return options
}

func validateRunbookOptions(options RunbookOptions) error {
	switch options.BootstrapMethod {
	case BootstrapMethodSnapshot, BootstrapMethodMithril:
		return nil
	default:
		return fmt.Errorf("unsupported bootstrap method %q", options.BootstrapMethod)
	}
}

func dolosBootstrapCommand(report *DolosReport, options RunbookOptions) string {
	switch options.BootstrapMethod {
	case BootstrapMethodMithril:
		downloadDir := filepath.Join(report.Dir, "snapshot")
		return fmt.Sprintf("dolos bootstrap mithril --download-dir %s --continue --retain-snapshot -c %s", shellQuote(downloadDir), shellQuote(report.ConfigPath))
	default:
		return fmt.Sprintf("dolos bootstrap snapshot --variant %s --point %s --continue -c %s", shellQuote(options.SnapshotVariant), shellQuote(options.SnapshotPoint), shellQuote(report.ConfigPath))
	}
}

func dolosDaemonCommand(report *DolosReport) string {
	return fmt.Sprintf("dolos daemon -c %s", shellQuote(report.ConfigPath))
}

func nectarConfigCommand(report *DolosReport, options RunbookOptions) string {
	parts := []string{
		"go run . bootstrap-dolos",
		"--dolos-dir " + shellQuote(report.Dir),
		"--config " + shellQuote(options.ConfigPath),
		"--driver " + shellQuote(options.Driver),
		"--profile " + shellQuote(options.Profile),
	}
	if strings.TrimSpace(options.MySQLDSN) != "" {
		parts = append(parts, "--mysql-dsn "+shellQuote(options.MySQLDSN))
	}
	parts = append(parts, "--write")
	return strings.Join(parts, " ")
}

func writeCommandBlock(b *strings.Builder, title string, command string) {
	fmt.Fprintf(b, "### %s\n\n", title)
	b.WriteString("```bash\n")
	b.WriteString(command)
	b.WriteString("\n```\n\n")
}

func readyWord(ok bool) string {
	if ok {
		return "ready"
	}
	return "pending"
}

func configuredWord(ok bool) string {
	if ok {
		return "configured"
	}
	return "pending"
}

func shellQuote(value string) string {
	if value == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}
